routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[
    'uses' => 'PortafolioController@index',
    'as'=> 'index'
]);



Auth::routes();

Route::get('contacto',[
    'uses' => 'PortafolioController@contacto',
    'as' => 'contacto'
    
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin',[
    'uses' => 'PortafolioController@admin',
    'as' => 'admin.admin' ])->middleware('auth');

Route::get('/{name}',[
    'uses' => 'PortafolioController@indexUsuario',
    'as' => 'indexUsuario'
]);

Route::post('indexSelect',[
    'uses' => 'PortafolioController@indexSelect',
    'as' => 'indexSelect'

]);

Route::get('{name}/contactoUsuario',[
    'uses' => 'PortafolioController@contactoUsuario',
     'as' => 'contactoUsuario'
]);

Route::get('{name}/jobs',[
    'uses' => 'PortafolioController@job',
    'as' => 'jobs'
]);

Route::get('{name}/expe',[
    'uses' => 'PortafolioController@expe',
    'as' => 'expe'
]);

Route::get('{name}/expe#empresas',[
    'uses' => 'PortafolioController@expe_empresas',
    'as' => 'expe#empresas'
]);

Route::get('{name}/expe#clientes',[
    'uses' => 'PortafolioController@expe_clientes',
    'as' => 'expe#clientes'
]);

Route::get('{name}/prefe',[
    'uses' => 'PortafolioController@prefe',
    'as' => 'prefe'
]);

Route::get('{name}/prefe#webs',[
    'uses' => 'PortafolioController@prefe_webs',
    'as' => 'prefe#webs'
]);

Route::get('{name}/prefe#videos',[
    'uses' => 'PortafolioController@prefe_videos',
    'as' => 'prefe#videos'
]);

Route::get('{name}/prefe#blogs',[
    'uses' => 'PortafolioController@prefe_blogs',
    'as' => 'prefe#blogs'
]);

Route::get('{name}/prefe#libros',[
    'uses' => 'PortafolioController@prefe_libros',
    'as' => 'prefe#libros'
]);

Route::get('{name}/prefe#otros',[
    'uses' => 'PortafolioController@prefe_otros',
    'as' => 'prefe#otros'
]);

Route::get('{name}/pdf',[
    'uses' => 'PdfController@invoice',
    'as' => 'pdf'
]);



Route::get('{name}/tit',[
    'uses' => 'PortafolioController@tit',
    'as' => 'tit'
]);

    Route::group(['prefix' => 'admin'
    ,'middleware'=>'auth'
    ], function(){
    Route::resource('jobAdmin','JobController');   
    Route::get('jobAdmin/{id}/destroy', [
    'uses' => 'jobController@destroy',
    'as' => 'jobAdmin.destroy'
    ]);
    
    Route::resource('expeAdmin', 'ExpeController');
    Route::get('expeAdmin/{id}/destroy', [
    'uses' => 'expeController@destroy',
    'as' => 'expeAdmin.destroy'
    ]);
    
    Route::resource('prefeAdmin', 'PrefeController');
    Route::get('prefeAdmin/{id}/destroy', [
    'uses' => 'prefeController@destroy',
    'as' => 'prefeAdmin.destroy'
    ]);
    
    Route::resource('titAdmin', 'TitController');
    Route::get('titAdmin/{id}/destroy', [
    'uses' => 'titController@destroy',
    'as' => 'titAdmin.destroy'
    ]);
    
    Route::resource('usuarioAdmin', 'UsuarioController');
    Route::get('usuarioAdmin/{id}/destroy', [
    'uses' => 'usuarioController@destroy',
    'as' => 'usuarioAdmin.destroy'
    ]);
    
    Route::resource('UserAdmin', 'useradminController');
    Route::get('UserAdmin/{id}/destroy', [
    'uses' => 'useradminController@destroy',
    'as' => 'UserAdmin.destroy'
    ]);
    
    Route::get('admin', [
    'uses' => 'PortafolioController@admin',
    'as' => 'admin.admin'
    ]);
    
    });
    
    

resources/views/admin/jobAdmin/create.blade.php
<!-- inicio -->
@extends ('template/baseAdmin')
@section('imag')
<img alt="header-banner-image" src="{{asset('img/adminR.png')}}" class='header-img' style='height: 300px'>
<div class="overlay overlay1">
            <div class="black inviewport animated delay4" data-effect="fadeInLeftOpacity"></div>
            <div class="primary inviewport animated delay4" data-effect="fadeInRightOpacity"></div>
</div>
@endsection
@section ('content')

    <!-- Admin - Start -->
<div class="row">
<h1 class="heading">Añadir Jobs</h1>
<h3 class="heading">{{$usuario->nombreCompleto}}</h3>
{!! Form::open(['route' => 'jobAdmin.store', 'method' =>'POST']) !!}
    <div class='form-group'>
        {!! Form::label('nombre', 'Nombre') !!}
        {!! Form::text('nombre', null,['class' => 'form-control','required','maxlength=255','minlength=1'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('enlace', 'Enlace') !!}
        {!! Form::url('enlace', null,['class' => 'form-control', 'required','maxlength=255','minlength=8' ]) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('imagen', 'Imagen') !!}
        {!! Form::url('imagen', null,['class' => 'form-control', 'required','maxlength=1020','minlength=8'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('descripcion', 'Descripcion') !!}
        {!! Form::text('descripcion', null,['class' => 'form-control', 'required','maxlength=1020','minlength=1'] ) !!}
    </div>
    <div>
        {{ Form::hidden('id_user', Auth::id()) }}
    </div>
<!--<input type="text" hidden="hidden" name="id_user" value="{{Auth::id()}}"/>-->
    <div class='form-group'>
        <button type="submit" class="btn-sm btn-info">
            <span class='glyphicon glyphicon-floppy-disk'> REGISTRAR </span>
        </button>
 
    </div>
{!! Form::close() !!}
</div>
<!-- End - Admin -->
@endsection

resources/views/admin/jobAdmin/edit.blade.php
<!-- inicio -->
@extends ('template/baseAdmin')
@section('imag')
<img alt="header-banner-image" src="{{asset('img/adminR.png')}}" class='header-img' style='height: 300px'>
<div class="overlay overlay1">
            <div class="black inviewport animated delay4" data-effect="fadeInLeftOpacity"></div>
            <div class="primary inviewport animated delay4" data-effect="fadeInRightOpacity"></div>
</div>
@endsection
@section ('content')
    <!-- Admin - Start -->
<div class="row">
<h1 class="heading">EDITAR JOBS</h1>
<h3 class="heading">{{$usuario->nombreCompleto}}</h3>
{!! Form::open(['route' => ['jobAdmin.update', $job],'method' =>'PUT']) !!}
    <div class='form-group'>
        {!! Form::label('nombre', 'Nombre') !!}
        {!! Form::text('nombre', $job->nombre,['class' => 'form-control','required','maxlength=255','minlength=1'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('enlace', 'Enlace') !!}
        {!! Form::url('enlace', $job->enlace,['class' => 'form-control', 'required','maxlength=255','minlength=8' ]) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('imagen', 'Imagen') !!}
        {!! Form::url('imagen', $job->imagen,['class' => 'form-control', 'required','maxlength=1020','minlength=8'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('descripcion', 'Descripcion') !!}
        {!! Form::text('descripcion', $job->descripcion,['class' => 'form-control', 'required','maxlength=1020','minlength=1'] ) !!}
    </div>
    <div>
        {{ Form::hidden('id_user', $job->id_user) }}
    </div>
    <div class='form-group'>
        <button type="submit" class="btn-sm btn-info">
            <span class='glyphicon glyphicon-floppy-disk'> REGISTRAR </span>
        </button>
    </div>
{!! Form::close() !!}
</div>
<!-- End - Admin -->
@endsection

resources/views/admin/jobAdmin/index.blade.php
<!-- inicio -->
@extends ('template/baseAdmin')
@section('imag')
<img alt="header-banner-image" src="{{asset('img/adminR.png')}}" class='header-img' style='height: 300px'>
<div class="overlay overlay1">
            <div class="black inviewport animated delay4" data-effect="fadeInLeftOpacity"></div>
            <div class="primary inviewport animated delay4" data-effect="fadeInRightOpacity"></div>
</div>
@endsection

@section ('content')
<div class="row">
    <h1 class="heading">ADMINISTRACION DE JOBS</h1>
    <div class="headul"></div>
    <h3 class="heading">{{$usuario->nombreCompleto}}</h3>
<div class='container table-responsive '>
    <a href="{{route ('jobAdmin.create')}}" class='btn-sm btn-info'>
    <span class='glyphicon glyphicon-floppy-disk'> NUEVO </span>
    </a>
<table class='table' >
    <thead>
    <td>EDITAR</td>
    <td>BORRAR</td> 
    <td>ID</td>
    <td>NOMBRE</td>
    <td>ENLACE</td>
    <td>IMAGEN</td>
    <td>DESCRIPCION</td>
    </thead>
    <tbody>
        
        @foreach($jobs as $job)
        @if($job->id_user == Auth::id())
        <tr>
        <td>
            <a href="{{route('jobAdmin.edit', $job->id )}}" class='btn-sm btn-warning '> 
                <span class='glyphicon glyphicon-cog'></span>
            </a>
        </td>
        <td>
         <a href="{{route('jobAdmin.destroy', $job->id)}}" id="{{$job->nombre}}"  class='btnPromt btn-sm btn-danger'>
<span class='glyphicon glyphicon-trash'></span>
            </a>
        </td>
        <td>{{$job->id}}</td>
        <td>{{$job->nombre}}</td>
        <td>{{substr($job->enlace, 0, 20)}}...</td>
        <td><img src='{{str_replace("www.dropbox", "dl.dropboxusercontent",$job->imagen)}}' class='img-responsive' style="height: 40px; width: 60px"></td>
        <td>{{substr($job->descripcion, 0, 20)}}...</td>
        </tr>
        @endif
        @endforeach
    </tbody>
</table>
</div>
{!! $jobs->render() !!}

</div>


@endsection