routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[
    'uses' => 'PortafolioController@index',
    'as'=> 'index'
]);



Auth::routes();

Route::get('contacto',[
    'uses' => 'PortafolioController@contacto',
    'as' => 'contacto'
    
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin',[
    'uses' => 'PortafolioController@admin',
    'as' => 'admin.admin' ])->middleware('auth');

Route::get('/{name}',[
    'uses' => 'PortafolioController@indexUsuario',
    'as' => 'indexUsuario'
]);

Route::post('indexSelect',[
    'uses' => 'PortafolioController@indexSelect',
    'as' => 'indexSelect'

]);

Route::get('{name}/contactoUsuario',[
    'uses' => 'PortafolioController@contactoUsuario',
     'as' => 'contactoUsuario'
]);

Route::get('{name}/jobs',[
    'uses' => 'PortafolioController@job',
    'as' => 'jobs'
]);

Route::get('{name}/expe',[
    'uses' => 'PortafolioController@expe',
    'as' => 'expe'
]);

Route::get('{name}/expe#empresas',[
    'uses' => 'PortafolioController@expe_empresas',
    'as' => 'expe#empresas'
]);

Route::get('{name}/expe#clientes',[
    'uses' => 'PortafolioController@expe_clientes',
    'as' => 'expe#clientes'
]);

Route::get('{name}/prefe',[
    'uses' => 'PortafolioController@prefe',
    'as' => 'prefe'
]);

Route::get('{name}/prefe#webs',[
    'uses' => 'PortafolioController@prefe_webs',
    'as' => 'prefe#webs'
]);

Route::get('{name}/prefe#videos',[
    'uses' => 'PortafolioController@prefe_videos',
    'as' => 'prefe#videos'
]);

Route::get('{name}/prefe#blogs',[
    'uses' => 'PortafolioController@prefe_blogs',
    'as' => 'prefe#blogs'
]);

Route::get('{name}/prefe#libros',[
    'uses' => 'PortafolioController@prefe_libros',
    'as' => 'prefe#libros'
]);

Route::get('{name}/prefe#otros',[
    'uses' => 'PortafolioController@prefe_otros',
    'as' => 'prefe#otros'
]);

Route::get('{name}/pdf',[
    'uses' => 'PdfController@invoice',
    'as' => 'pdf'
]);



Route::get('{name}/tit',[
    'uses' => 'PortafolioController@tit',
    'as' => 'tit'
]);

    Route::group(['prefix' => 'admin'
    ,'middleware'=>'auth'
    ], function(){
    Route::resource('jobAdmin','JobController');   
    Route::get('jobAdmin/{id}/destroy', [
    'uses' => 'jobController@destroy',
    'as' => 'jobAdmin.destroy'
    ]);
    
    Route::resource('expeAdmin', 'ExpeController');
    Route::get('expeAdmin/{id}/destroy', [
    'uses' => 'expeController@destroy',
    'as' => 'expeAdmin.destroy'
    ]);
    
    Route::resource('prefeAdmin', 'PrefeController');
    Route::get('prefeAdmin/{id}/destroy', [
    'uses' => 'prefeController@destroy',
    'as' => 'prefeAdmin.destroy'
    ]);
    
    Route::resource('titAdmin', 'TitController');
    Route::get('titAdmin/{id}/destroy', [
    'uses' => 'titController@destroy',
    'as' => 'titAdmin.destroy'
    ]);
    
    Route::resource('usuarioAdmin', 'UsuarioController');
    Route::get('usuarioAdmin/{id}/destroy', [
    'uses' => 'usuarioController@destroy',
    'as' => 'usuarioAdmin.destroy'
    ]);
    
    Route::resource('UserAdmin', 'useradminController');
    Route::get('UserAdmin/{id}/destroy', [
    'uses' => 'useradminController@destroy',
    'as' => 'UserAdmin.destroy'
    ]);
    
    Route::get('admin', [
    'uses' => 'PortafolioController@admin',
    'as' => 'admin.admin'
    ]);
    
    });
    
    

resources/views/admin/UsuarioAdmin/create.blade.php
<!-- inicio -->
@extends ('template/baseAdmin')
@section('imag')
<img alt="header-banner-image" src="{{asset('img/adminR.png')}}" class='header-img' style='height: 300px'>
<div class="overlay overlay1">
            <div class="black inviewport animated delay4" data-effect="fadeInLeftOpacity"></div>
            <div class="primary inviewport animated delay4" data-effect="fadeInRightOpacity"></div>
</div>
@endsection
@section ('content')
    <!-- Admin - Start -->
<div class="row">
<h1 class="heading">USUARIO</h1>
<div class="headul"></div>
<h3 class="heading">{{$name}}</h3>
        
{!! Form::open(['route' => 'usuarioAdmin.store', 'method' =>'POST']) !!}
    <div class='form-group'>
        {!! Form::label('presentacion', 'Presentacion') !!}
        {!! Form::textArea('presentacion', null,['size' => '30x5','class' => 'form-control','required','maxlength=2040','minlength=1','maxlength=2040' ] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('nombreCompleto', 'Nombre') !!}
        {!! Form::text('nombreCompleto', null,['class' => 'form-control','required','maxlength=255','minlength=1'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('profesion', 'Profesion') !!}
        {!! Form::text('profesion', null,['class' => 'form-control','required','maxlength=100','minlength=1'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('faceBook', 'FaceBook') !!}
        {!! Form::url('faceBook', null,['class' => 'form-control', 'required','maxlength=1020','minlength=8' ]) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('linkedIn', 'LinkedIn') !!}
        {!! Form::url('linkedIn', null,['class' => 'form-control', 'required','maxlength=1020','minlength=8' ]) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('otraredsocial', 'Otra Red Social') !!}
        {!! Form::url('otraRedSocial', null,['class' => 'form-control', 'required','maxlength=1020','minlength=8' ]) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('imagen', 'Imagen') !!}
        {!! Form::url('imagen', null,['class' => 'form-control', 'required','maxlength=1020','minlength=1'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('zonageografica', 'Zona Geográfica') !!}
        {!! Form::text('zonaGeografica', null,['class' => 'form-control','required','maxlength=255','minlength=1'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('telefono', 'Teléfono') !!}
        {!! Form::text('telefono', null,['class' => 'form-control','numeric|required','maxlength=100','minlength=1'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('email', 'Email') !!}
        {!! Form::text('email', null,['class' => 'form-control','required','maxlength=255','minlength=1'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('enlacewebpersonal', 'Enlace Web Personal') !!}
        {!! Form::url('enlaceWebPersonal', null,['class' => 'form-control', 'required','maxlength=1020','minlength=8' ]) !!}
    </div>
    <div>
        {{ Form::hidden('id_user', $user->id) }}
    </div>
    <div class='form-group'>
        <button type="submit" class="btn-sm btn-info">
            <span class='glyphicon glyphicon-floppy-disk'> REGISTRAR </span>
        </button>
 
    </div>
{!! Form::close() !!}
</div>
<!-- End - Admin -->
@endsection

resources/views/admin/UsuarioAdmin/edit.blade.php
<!-- inicio -->
@extends ('template/baseAdmin')
@section('imag')
<img alt="header-banner-image" src="{{asset('img/adminR.png')}}" class='header-img' style='height: 300px'>
<div class="overlay overlay1">
            <div class="black inviewport animated delay4" data-effect="fadeInLeftOpacity"></div>
            <div class="primary inviewport animated delay4" data-effect="fadeInRightOpacity"></div>
</div>
@endsection
@section ('content')
    <!-- Admin - Start -->
<div class="row">
<h1 class="heading">EDITAR DATOS DE USUARIO </h1>
<div class="headul"></div>
<h3 class="heading">{{$name}}</h3>
{!! Form::open(['route' => ['usuarioAdmin.update', $usuario],'method' =>'PUT']) !!}
<div class='form-group'>
        {!! Form::label('presentacion', 'Presentacion') !!}
        {!! Form::textArea('presentacion',$usuario->presentacion,['size' => '30x5','class' => 'form-control','required','maxlength=2040','minlength=1','maxlength=2040' ] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('nombreCompleto', 'Nombre') !!}
        {!! Form::text('nombreCompleto', $usuario->nombreCompleto,['class' => 'form-control','required','maxlength=50','minlength=1'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('profesion', 'Profesion') !!}
        {!! Form::text('profesion', $usuario->profesion,['class' => 'form-control','required','maxlength=255','minlength=1'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('faceBook', 'FaceBook') !!}
        {!! Form::url('faceBook', $usuario->faceBook,['class' => 'form-control', 'required','maxlength=255','minlength=8' ]) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('linkedIn', 'LinkedIn') !!}
        {!! Form::url('linkedIn', $usuario->linkedIn,['class' => 'form-control', 'required','maxlength=255','minlength=8' ]) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('otraredsocial', 'Otra Red Social') !!}
        {!! Form::url('otraRedSocial', $usuario->otraRedSocial,['class' => 'form-control', 'required','maxlength=255','minlength=8' ]) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('imagen', 'Imagen') !!}
        {!! Form::url('imagen', $usuario->imagen,['class' => 'form-control', 'required','maxlength=255','minlength=1'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('zonageografica', 'Zona Geográfica') !!}
        {!! Form::text('zonaGeografica', $usuario->zonaGeografica,['class' => 'form-control','required','maxlength=255','minlength=1'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('telefono', 'Teléfono') !!}
        {!! Form::text('telefono', $usuario->telefono,['class' => 'form-control','numeric|required','maxlength=10','minlength=1'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('email', 'Email') !!}
        {!! Form::text('email', $usuario->email,['class' => 'form-control','required','maxlength=255','minlength=1'] ) !!}
    </div>
    <div class='form-group'>
        {!! Form::label('enlacewebpersonal', 'Enlace Web Personal') !!}
        {!! Form::url('enlaceWebPersonal', $usuario->enlaceWebPersonal,['class' => 'form-control', 'required','maxlength=255','minlength=8' ]) !!}
    </div>
    <div>
        {{ Form::hidden('id_user', $usuario->id_user) }}
    </div>
    <div class='form-group'>
        <button type="submit" class="btn-sm btn-info">
            <span class='glyphicon glyphicon-floppy-disk'> REGISTRAR </span>
        </button>
    </div>
   
{!! Form::close() !!}
</div>
<!-- End - Admin -->
@endsection

resources/views/admin/UsuarioAdmin/index.blade.php
<!-- inicio -->
@extends ('template/baseAdmin')
@section('imag')
<img alt="header-banner-image" src="{{asset('img/adminR.png')}}" class='header-img' style='height: 300px'>
<div class="overlay overlay1">
    <div class="black inviewport animated delay4" data-effect="fadeInLeftOpacity"></div>
    <div class="primary inviewport animated delay4" data-effect="fadeInRightOpacity"></div>
</div>
@endsection
@section ('content')
<!-- Admin - Start -->

<div class="row">
    <h1 class="heading">DATOS DE USUARIO</h1>
    <div class="headul"></div>
    <h3 class="heading">{{$name}}</h3>
    <div class='container table-responsive '>
        @if(!$usuario)
        
        <a href="{{route ('usuarioAdmin.create')}}" class='btn btn-info center-block'>
            <span class='glyphicon glyphicon-floppy-disk'> INTRODUCIR DATOS DE USUARIO POR PIMERA VEZ </span>
        </a>
        
        @endif
        @if($usuario)
        <a href="{{route('usuarioAdmin.edit', Auth::id())}}" class='btn-sm btn-warning '> 
            <span class='glyphicon glyphicon-cog'> CAMBIAR DATOS</span>
        </a>
        <hr>
        
        <ul class='list-group ' >
            <li class="list-group-item list-group-item-info">ID: {{$usuario->id_user}}</li>
            <li class="list-group-item list-group-item-info">PRESENTACIÓN: {{$usuario->presentacion}}</li>
            <li class="list-group-item list-group-item-info">NOMBRE COMPLETO: {{$usuario->nombreCompleto}}</li>
            <li class="list-group-item list-group-item-info">PROFESION: {{$usuario->profesion}}</li>
            <li class="list-group-item list-group-item-warning">FACEBOOK: {{$usuario->faceBook}}</li>
            <li class="list-group-item list-group-item-warning">LINKEDIN: {{$usuario->linkedIn}}</li>
            <li class="list-group-item list-group-item-warning">OTRA RED SOCIAL: {{$usuario->otraRedSocial}}</li>
            <li class="list-group-item list-group-item-info">IMAGEN: <img src='{{str_replace("www.dropbox", "dl.dropboxusercontent",$usuario->imagen)}}' class='img-responsive' style="height: 100px; width: 140px"></li>
            <li class="list-group-item list-group-item-info">ZONA GEOGRAFICA: {{$usuario->zonaGeografica}}</li>
            <li class="list-group-item list-group-item-info">TELÉFONO: {{$usuario->telefono}}</li>
            <li class="list-group-item list-group-item-success">EMAIL: {{$usuario->email}}</li>
            <li class="list-group-item list-group-item-warning">ENLACE WEB PERSONAL: {{$usuario->enlaceWebPersonal}}</li>
        </ul>
    
        <!--
                    <a href="{{route('usuarioAdmin.destroy', $usuario->id)}}" id="{{$usuario->nombre}}"  class='btnPromt btn-sm btn-danger'>
                        <span class='glyphicon glyphicon-trash'></span>
                    </a>-->

        @endif
        
    </div>
</div>
<!-- End - Admin -->









@endsection